package dev.talosdx.cms.model.entity

import dev.talosdx.cms.model.entity.prototype.BaseStringNotAutoGeneratedIdAuditEntity
import jakarta.persistence.Entity
import jakarta.persistence.FetchType
import jakarta.persistence.OneToMany
import jakarta.persistence.Table
import org.springframework.context.annotation.Lazy

@Entity
@Table(name = "component")
class CMSComponent(
    id: String,
    var name: String = "component.$id.name",
    var description: String = "component.$id.description",
    @Lazy
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "component")
    val permissions: MutableSet<Permission> = mutableSetOf(),
) : BaseStringNotAutoGeneratedIdAuditEntity(id) {
}