package dev.talosdx.cms.model.entity

import dev.talosdx.cms.model.entity.prototype.BaseStringNotAutoGeneratedIdAuditEntity
import jakarta.persistence.Entity
import jakarta.persistence.FetchType
import jakarta.persistence.OneToMany
import jakarta.persistence.Table
import org.springframework.context.annotation.Lazy

@Entity
@Table(name = "language")
class Language(
    isoFormattedId: String,
    val isEnabled: Boolean = true,
    val isDefault: Boolean = false,
    @Lazy
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
    val translations: MutableSet<I18n> = mutableSetOf(),
) : BaseStringNotAutoGeneratedIdAuditEntity(isoFormattedId) {
}


