package dev.talosdx.cms.model.entity

import dev.talosdx.cms.model.entity.prototype.BaseStringNotAutoGeneratedIdAuditEntity
import jakarta.persistence.*
import org.springframework.context.annotation.Lazy
import org.springframework.security.core.GrantedAuthority
import org.springframework.security.core.authority.SimpleGrantedAuthority

@Entity
@Table(name = "permission")
class Permission(
    id: String,
    @Column(name = "name", unique = false, nullable = false)
    var name: String = "permission.$id.name",

    @Column(name = "description", unique = false, nullable = false)
    var description: String = "permission.$id.description",

    @Lazy
    @ManyToOne(fetch = FetchType.LAZY)
    var component: CMSComponent? = null,
) : BaseStringNotAutoGeneratedIdAuditEntity(id) {
    fun toGrandAuthority(): GrantedAuthority = SimpleGrantedAuthority(id)
}

