package dev.talosdx.cms.model.entity

import dev.talosdx.cms.model.entity.prototype.BaseStringNotAutoGeneratedIdAuditEntity
import jakarta.persistence.Entity
import jakarta.persistence.Table

@Entity
@Table(name = "system_settings")
class SystemSettings(
    id: String,
    val value: String,
) : BaseStringNotAutoGeneratedIdAuditEntity(id) {
}