package dev.talosdx.cms.model.entity.prototype

import jakarta.persistence.Column
import jakarta.persistence.EntityListeners
import jakarta.persistence.Id
import jakarta.persistence.MappedSuperclass
import org.springframework.data.jpa.domain.support.AuditingEntityListener
import org.springframework.data.util.ProxyUtils

@MappedSuperclass
@EntityListeners(AuditingEntityListener::class)
abstract class BaseStringNotAutoGeneratedIdAuditEntity(
    @Id
    @Column(name = "id", nullable = false, unique = true)
    open var id: String?,
) : BaseAuditEntity() {
    override fun equals(other: Any?): Boolean {
        other ?: return false

        if (this === other) return true

        if (javaClass != ProxyUtils.getUserClass(other)) return false

        other as BaseStringNotAutoGeneratedIdAuditEntity

        return this.id != null && this.id == other.id
    }

    override fun hashCode() = javaClass.hashCode()

    override fun toString(): String {
        return "${this.javaClass.simpleName}(id=$id)"
    }
}