package dev.talosdx.cms.model.entity.prototype

import jakarta.persistence.Column
import jakarta.persistence.EntityListeners
import jakarta.persistence.Id
import jakarta.persistence.MappedSuperclass
import org.springframework.data.jpa.domain.support.AuditingEntityListener

@MappedSuperclass
@EntityListeners(AuditingEntityListener::class)
abstract class BaseStringNotAutoGeneratedIdAuditEntity(
    @Id
    @Column(name = "id", nullable = false, unique = true)
    override var id: String?,
) : BaseIdAuditEntity<String>()