CREATE TABLE attachment
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    download_url  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_attachment PRIMARY KEY (id)
);

CREATE TABLE client
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email               VARCHAR(255)                            NOT NULL,
    username            VARCHAR(255)                            NOT NULL,
    password            VARCHAR(255)                            NOT NULL,
    user_role_id        BIGINT,
    registration_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_activated        BOOLEAN                                 NOT NULL,
    activation_code     VARCHAR(255),
    is_blocked          BOOLEAN                                 NOT NULL,
    blocking_date       TIMESTAMP WITHOUT TIME ZONE,
    blocking_until_date TIMESTAMP WITHOUT TIME ZONE,
    blocking_reason     VARCHAR(255),
    mail_id             BIGINT,
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE component
(
    id            VARCHAR(255)                NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    CONSTRAINT pk_component PRIMARY KEY (id)
);

CREATE TABLE content
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_date     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name              VARCHAR(255),
    short_description VARCHAR(255),
    text              VARCHAR(255),
    author_id         BIGINT,
    content_type      VARCHAR(255),
    attachment_id     BIGINT,
    CONSTRAINT pk_content PRIMARY KEY (id)
);

CREATE TABLE i18n
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    key           VARCHAR(255)                            NOT NULL,
    language_id   VARCHAR(255),
    translation   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_i18n PRIMARY KEY (id)
);

CREATE TABLE language
(
    id            VARCHAR(255)                NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_enabled    BOOLEAN,
    is_default    BOOLEAN,
    CONSTRAINT pk_language PRIMARY KEY (id)
);

CREATE TABLE mail
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    to_emails     VARCHAR(255)                            NOT NULL,
    from_email    VARCHAR(255)                            NOT NULL,
    header        VARCHAR(255)                            NOT NULL,
    body          VARCHAR(255)                            NOT NULL,
    from_user_id  BIGINT,
    is_sent       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_mail PRIMARY KEY (id)
);

CREATE TABLE permission
(
    id            VARCHAR(255)                NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    name          VARCHAR(255)                NOT NULL,
    description   VARCHAR(255)                NOT NULL,
    component_id  VARCHAR(255),
    CONSTRAINT pk_permission PRIMARY KEY (id)
);

CREATE TABLE system_settings
(
    id            VARCHAR(255)                NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    value         VARCHAR(255),
    CONSTRAINT pk_system_settings PRIMARY KEY (id)
);

CREATE TABLE user_role
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    description   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (id)
);

CREATE TABLE user_role_to_permissions
(
    permission_id VARCHAR(255) NOT NULL,
    user_role_id  BIGINT       NOT NULL,
    CONSTRAINT pk_user_role_to_permissions PRIMARY KEY (permission_id, user_role_id)
);

CREATE TABLE user_to_permissions
(
    permission_id VARCHAR(255) NOT NULL,
    user_id       BIGINT       NOT NULL,
    CONSTRAINT pk_user_to_permissions PRIMARY KEY (permission_id, user_id)
);

ALTER TABLE client
    ADD CONSTRAINT uc_client_email UNIQUE (email);

ALTER TABLE client
    ADD CONSTRAINT uc_client_username UNIQUE (username);

ALTER TABLE component
    ADD CONSTRAINT uc_component_id UNIQUE (id);

ALTER TABLE language
    ADD CONSTRAINT uc_language_id UNIQUE (id);

ALTER TABLE permission
    ADD CONSTRAINT uc_permission_id UNIQUE (id);

ALTER TABLE system_settings
    ADD CONSTRAINT uc_system_settings_id UNIQUE (id);

ALTER TABLE client
    ADD CONSTRAINT FK_CLIENT_ON_MAIL FOREIGN KEY (mail_id) REFERENCES mail (id);

ALTER TABLE client
    ADD CONSTRAINT FK_CLIENT_ON_USERROLE FOREIGN KEY (user_role_id) REFERENCES user_role (id);

ALTER TABLE content
    ADD CONSTRAINT FK_CONTENT_ON_ATTACHMENT FOREIGN KEY (attachment_id) REFERENCES attachment (id);

ALTER TABLE content
    ADD CONSTRAINT FK_CONTENT_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES client (id);

ALTER TABLE i18n
    ADD CONSTRAINT FK_I18N_ON_LANGUAGE FOREIGN KEY (language_id) REFERENCES language (id);

ALTER TABLE mail
    ADD CONSTRAINT FK_MAIL_ON_FROMUSER FOREIGN KEY (from_user_id) REFERENCES client (id);

ALTER TABLE permission
    ADD CONSTRAINT FK_PERMISSION_ON_COMPONENT FOREIGN KEY (component_id) REFERENCES component (id);

ALTER TABLE user_role_to_permissions
    ADD CONSTRAINT fk_useroltoper_on_permission FOREIGN KEY (permission_id) REFERENCES permission (id);

ALTER TABLE user_role_to_permissions
    ADD CONSTRAINT fk_useroltoper_on_user_role FOREIGN KEY (user_role_id) REFERENCES user_role (id);

ALTER TABLE user_to_permissions
    ADD CONSTRAINT fk_usetoper_on_permission FOREIGN KEY (permission_id) REFERENCES permission (id);

ALTER TABLE user_to_permissions
    ADD CONSTRAINT fk_usetoper_on_user FOREIGN KEY (user_id) REFERENCES client (id);