spring:
  datasource:
    url: jdbc:postgresql://database:5432/cms?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: cmsuser
    password: cmspassword
devtools:
  add-properties: false