version: "3.8"

services:
  database:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_DB: cms
      POSTGRES_USER: cmsuser
      POSTGRES_PASSWORD: cmspassword
    ports:
      - "5432:5432"
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
